export const hehe: string;
export const header: string;
export const body: string;
export const person: string;
export const personLeft: string;
export const personAvatar: string;
export const emptyPage: string;
export const reload: string;
export const personRight: string;
