export const page: string;
export const header: string;
export const back: string;
export const title: string;
export const tt1: string;
export const tt2: string;
export const tt3: string;
export const tt4: string;
export const tt5: string;
